# NumPy Basics

## Introduction to NumPy
NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides support for arrays, matrices, and a variety of high-level mathematical functions to operate on these data structures.

In [20]:
import numpy as np

## Creating Arrays
### 1. Creating a NumPy Array

In [21]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [22]:
# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


### 2. Arrays with Default Values

In [23]:
# Array of zeros
zeros = np.zeros((3, 3))
print("Zeros Array:\n", zeros)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# Array of ones
ones = np.ones((2, 4))
print("Ones Array:\n", ones)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
# Array with a range of values
range_array = np.arange(0, 10, 2)
print("Range Array:", range_array)

Range Array: [0 2 4 6 8]


In [26]:
# Empty array (values will be uninitialized)
empty = np.empty((2, 3))
print("Empty Array:\n", empty)

Empty Array:
 [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [27]:
# Linearly spaced array
linspace_array = np.linspace(0, 1, 5)
print("Linearly Spaced Array:", linspace_array)


Linearly Spaced Array: [0.   0.25 0.5  0.75 1.  ]


## Basic Array Operations
### 1. Arithmetic Operations

In [28]:

arr = np.array([1, 2, 3, 4])


In [29]:
# Element-wise addition
print("Add 2:", arr + 2)

Add 2: [3 4 5 6]


In [30]:
# Element-wise subtraction
print("Subtract 1:", arr - 1)

Subtract 1: [0 1 2 3]


In [31]:
# Element-wise multiplication
print("Multiply by 3:", arr * 3)

# Element-wise division
print("Divide by 2:", arr / 2)

# Element-wise power
print("Squared:", arr ** 2)

Multiply by 3: [ 3  6  9 12]
Divide by 2: [0.5 1.  1.5 2. ]
Squared: [ 1  4  9 16]


### 2. Mathematical Functions

In [32]:
arr = np.array([0, np.pi / 2, np.pi])

In [33]:
# Trigonometric functions
print("Sin:", np.sin(arr))
print("Cos:", np.cos(arr))

# Exponential and logarithm
print("Exponential:", np.exp(arr))
print("Natural Log:", np.log(arr + 1))

Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponential: [ 1.          4.81047738 23.14069263]
Natural Log: [0.         0.94421571 1.42108041]


## Indexing and Slicing
### 1. Basic Indexing

In [34]:

arr = np.array([10, 20, 30, 40, 50])

In [35]:
# Accessing elements
print("First element:", arr[0])
print("Last element:", arr[-1])

First element: 10
Last element: 50


### 2. Slicing Arrays

In [36]:
# Slicing
print("Elements from index 1 to 3:", arr[1:4])
print("Elements with step of 2:", arr[::2])

Elements from index 1 to 3: [20 30 40]
Elements with step of 2: [10 30 50]


### 3. Indexing in 2D Arrays

In [37]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [38]:
# Accessing elements
print("Element at (1, 2):", arr2[1, 2])

# Slicing rows and columns
print("First row:", arr2[0, :])
print("First column:", arr2[:, 0])

Element at (1, 2): 6
First row: [1 2 3]
First column: [1 4 7]



## Shape and Reshape
### 1. Array Shape

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)

Shape: (2, 3)


### 2. Reshaping Arrays

In [40]:
reshaped = arr.reshape(3, 2)
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


## Array Concatenation and Splitting
### 1. Concatenation

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


In [42]:
# Concatenate along 1D
concatenated = np.concatenate((arr1, arr2))
print("Concatenated Array:", concatenated)

Concatenated Array: [1 2 3 4 5 6]


### 2. Splitting

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [44]:
# Split into three parts
split = np.array_split(arr, 3)
print("Split Arrays:", split)

Split Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


## Useful Array Functions
### 1. Statistical Functions

In [45]:
arr = np.array([1, 2, 3, 4, 5])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


### 2. Array Sorting

In [46]:
unsorted = np.array([3, 1, 2, 5, 4])
print("Sorted Array:", np.sort(unsorted))

Sorted Array: [1 2 3 4 5]


## Random Number Generation

In [ ]:
# Random integers
rand_ints = np.random.randint(0, 10, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random floats
rand_floats = np.random.rand(3, 3)
print("Random Floats:\n", rand_floats)

# Normal distribution
rand_norm = np.random.randn(3, 3)
print("Random Normal Distribution:\n", rand_norm)